# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Emitron' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Emitron
  pod 'Kingfisher', '~> 5.0'
  pod 'SwiftyJSON', '~> 4.0'
  pod 'Firebase/Core'
  pod 'Fabric', '~> 1.10.2'
  pod 'Crashlytics', '~> 3.13.2'
  pod 'KeychainSwift', '~> 16.0'

end
