# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc 'Push a new beta build to TestFlight'
  lane :ci_beta do
    setup_ci(provider: 'travis', force: true) # Until GA are properly supported
    sync_code_signing(type: 'appstore', readonly: true)
    build_app(project: 'Emitron.xcodeproj', scheme: 'Emitron')
    upload_to_testflight(skip_waiting_for_build_processing: true)
    slack(message: 'emitron successfully uploaded to TestFlight!')
  end

  lane :tests do
    run_tests(scheme: 'Emitron')
  end
end
